// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLibcapAndInstall() {
  return window['go']['main']['App']['CheckLibcapAndInstall']();
}

export function GetAllDevices() {
  return window['go']['main']['App']['GetAllDevices']();
}

export function GetPacketStream() {
  return window['go']['main']['App']['GetPacketStream']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsRoot() {
  return window['go']['main']['App']['IsRoot']();
}

export function LoadYaraRules(arg1, arg2) {
  return window['go']['main']['App']['LoadYaraRules'](arg1, arg2);
}

export function ParseSuricataRules(arg1, arg2) {
  return window['go']['main']['App']['ParseSuricataRules'](arg1, arg2);
}

export function StartCapture(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartCapture'](arg1, arg2, arg3, arg4, arg5);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
