// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLibcapAndInstall() {
  return ObfuscatedCall(0, []);
}

export function GetAllDevices() {
  return ObfuscatedCall(1, []);
}

export function GetPacketStream() {
  return ObfuscatedCall(2, []);
}

export function Greet(arg1) {
  return ObfuscatedCall(3, [arg1]);
}

export function IsRoot() {
  return ObfuscatedCall(4, []);
}

export function LoadYaraRules(arg1, arg2) {
  return ObfuscatedCall(5, [arg1, arg2]);
}

export function ParseSuricataRules(arg1, arg2) {
  return ObfuscatedCall(6, [arg1, arg2]);
}

export function StartCapture(arg1, arg2, arg3, arg4, arg5) {
  return ObfuscatedCall(7, [arg1, arg2, arg3, arg4, arg5]);
}

export function StopCapture() {
  return ObfuscatedCall(8, []);
}
