// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gopacket} from '../models';

export function CheckLibcapAndInstall():Promise<number>;

export function GetAllDevices():Promise<string>;

export function GetPacketStream():Promise<Array<gopacket.Packet>>;

export function Greet(arg1:string):Promise<string>;

export function IsRoot():Promise<boolean>;

export function StartCapture(arg1:string,arg2:boolean,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;

export function StopCapture():Promise<void>;
